Homework 1
================
Kehan Su ks4186
2024-09-21

\##Problem 1

``` r
data("penguins", package = "palmerpenguins")
view(penguins)
```

``` r
nrow_penguins = nrow(penguins)
ncol_penguins = ncol(penguins)
mean_flipper_length = mean(pull(penguins, flipper_length_mm), na.rm = TRUE)

nrow_penguins
```

    ## [1] 344

``` r
ncol_penguins
```

    ## [1] 8

``` r
mean_flipper_length
```

    ## [1] 200.9152

data description:

The data includes the information of 344 penguins from 2007 to
2009.There are 8 variables: species, island, bill length, bill depth,
flipper length, body mass, sex, and year.

The mean flipper length is 200.9152 mm.

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_ks4186_files/figure-gfm/plot-1.png)<!-- -->

``` r
ggsave("flipper_vs_bill_scatterplot.png")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).
