---
title: "Homework 1"
author: "Kehan Su ks4186"
date: 2024-09-21
output: github_document
---

```{r echo = FALSE, message = FALSE}
library(tidyverse)
```

## Problem 1


```{r data import}
data("penguins", package = "palmerpenguins")
view(penguins)
```

```{r info check}
nrow_penguins = nrow(penguins)
ncol_penguins = ncol(penguins)
mean_flipper_length = mean(pull(penguins, flipper_length_mm), na.rm = TRUE)

nrow_penguins
ncol_penguins
mean_flipper_length
```

data description:

The data includes the information of 344 penguins from 2007 to 2009.There are 8 variables: species, island, bill length, bill depth, flipper length, body mass, sex, and year.

The mean flipper length is 200.9152 mm.

```{r plot}
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
ggsave("flipper_vs_bill_scatterplot.png")
```


## Problem 2
```{r}
problem2_df = tibble (
  vec_number = rnorm(10),
  vec_logical = vec_number > 0,
  char_vec = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J"),
  factor_vec = factor(c("level1","level1","level1","level2","level2","level2","level2","level3","level3","level3"))
)
view(problem2_df)
```

